package com.paidflow.app;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.os.Bundle;
import android.os.Build;
import android.print.PrintAttributes;
import android.print.PrintManager;
import android.provider.MediaStore;
import android.util.AtomicFile;
import android.view.WindowInsets;
import android.webkit.*;
import android.widget.FrameLayout;
import com.googlecode.tesseract.android.TessBaseAPI;
import org.json.JSONObject;
import java.io.*;
import java.nio.charset.StandardCharsets;

public final class MainActivity extends Activity {
    private WebView web,printWeb;
    private AtomicFile dataFile;
    private File captureFile;
    private Uri captureUri,pendingShareUri;
    private String scanTarget="invoice",scanDraft="",pendingScanScript="";
    private boolean restoreScanDraft,scanBusy;
    private boolean pageReady,shareHandled;
    private static final int MAX=10*1024*1024,MAX_SCAN=25*1024*1024,EXPORT=101,IMPORT=102,SCAN=103;
    @Override @SuppressLint("SetJavaScriptEnabled") public void onCreate(Bundle state){
        super.onCreate(state);
        if(state!=null){scanTarget=state.getString("scanTarget","invoice");scanDraft=state.getString("scanDraft","");restoreScanDraft=!scanDraft.isEmpty();String savedUri=state.getString("captureUri");if(savedUri!=null){captureUri=Uri.parse(savedUri);captureFile=new File(new File(getCacheDir(),"scan"),captureUri.getLastPathSegment());}pendingScanScript=state.getString("pendingScanScript","");}
        dataFile=new AtomicFile(new File(getFilesDir(),"paidflow-v1.json"));
        FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(11,20,35));
        root.setOnApplyWindowInsetsListener((v,insets)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout());v.setPadding(bars.left,bars.top,bars.right,bars.bottom);return WindowInsets.CONSUMED;}v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});
        web=new WebView(this);web.setBackgroundColor(Color.rgb(11,20,35));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(false);web.getSettings().setAllowFileAccess(true);web.getSettings().setAllowContentAccess(false);web.getSettings().setAllowFileAccessFromFileURLs(false);web.getSettings().setAllowUniversalAccessFromFileURLs(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.getSettings().setSupportMultipleWindows(false);web.getSettings().setTextZoom(100);
        web.setWebViewClient(new WebViewClient(){
            @Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return true;}
            @Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){String url=request.getUrl().toString();if(url.startsWith("file:///android_asset/")&&!url.contains(".."))return null;return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}
            @Override public void onPageFinished(WebView view,String url){super.onPageFinished(view,url);if("file:///android_asset/index.html".equals(url))onWebReady();}
        });
        web.setWebChromeClient(new WebChromeClient());web.addJavascriptInterface(new Bridge(),"Native");root.addView(web,new FrameLayout.LayoutParams(-1,-1));setContentView(root);root.requestApplyInsets();web.loadUrl("file:///android_asset/index.html");receiveSharedImage(getIntent());
    }
    private boolean ru(){try{return new JSONObject(new String(dataFile.readFully(),StandardCharsets.UTF_8)).getJSONObject("settings").getString("language").equals("ru");}catch(Exception e){return java.util.Locale.getDefault().getLanguage().equals("ru");}}
    private String t(String r,String e){return ru()?r:e;}
    private void message(String text){runOnUiThread(()->{if(web!=null)web.evaluateJavascript("window.nativeMessage("+JSONObject.quote(text)+")",null);});}
    private byte[] read(InputStream input) throws IOException {if(input==null)throw new IOException();try(InputStream in=input;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>MAX)throw new IOException("Too large");out.write(b,0,n);}return out.toByteArray();}}
    private void chooseScanImage(String target,String draft){runOnUiThread(()->{if(scanBusy)return;scanDraft=draft!=null&&draft.length()<=200000?draft:"";new AlertDialog.Builder(this).setTitle("client".equals(target)?t("Добавить реквизиты по фото","Add business details from a photo"):t("Добавить изображение счёта","Add an invoice image")).setItems(ru()?new String[]{"Сфотографировать","Выбрать изображение"}:new String[]{"Take a photo","Choose an image"},(dialog,which)->{scanTarget=target;scanStatus(target,"busy",t("Ожидаю фотографию…","Waiting for an image…"));if(which==0)openInvoiceCamera();else openInvoicePicker();}).setNegativeButton(t("Отмена","Cancel"),null).show();});}
    private void openInvoiceCamera(){try{File dir=new File(getCacheDir(),"scan");if(!dir.exists()&&!dir.mkdirs())throw new IOException();captureFile=new File(dir,"capture-"+System.currentTimeMillis()+".jpg");captureUri=Uri.parse("content://com.paidflow.app.fileprovider/scan/"+captureFile.getName());Intent camera=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);camera.putExtra(MediaStore.EXTRA_OUTPUT,captureUri);camera.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);camera.setClipData(ClipData.newUri(getContentResolver(),"PaidFlow document",captureUri));startActivityForResult(camera,SCAN);}catch(Exception e){deleteCapture();scanStatus(scanTarget,"error",t("Не удалось открыть камеру. Нажми распознавание ещё раз и выбери готовое изображение.","Could not open the camera. Scan again and choose an existing image."));}}
    private void openInvoicePicker(){try{Intent picker=new Intent(Intent.ACTION_OPEN_DOCUMENT);picker.addCategory(Intent.CATEGORY_OPENABLE);picker.setType("image/*");startActivityForResult(picker,SCAN);}catch(Exception e){scanStatus(scanTarget,"error",t("Не удалось открыть выбор изображения. Повтори попытку.","Could not open the image picker. Try again."));}}
    private void deleteCapture(){if(captureFile!=null)captureFile.delete();captureFile=null;captureUri=null;}
    private File copyScanImage(Uri uri)throws IOException{File dir=new File(getCacheDir(),"scan");if(!dir.exists()&&!dir.mkdirs())throw new IOException("No scan cache");File file=new File(dir,"input-"+System.currentTimeMillis()+".img");try(InputStream in=getContentResolver().openInputStream(uri);FileOutputStream out=new FileOutputStream(file)){if(in==null)throw new IOException("Cannot read image");byte[] bytes=new byte[8192];int count,total=0;while((count=in.read(bytes))!=-1){total+=count;if(total>MAX_SCAN)throw new IOException("Image too large");out.write(bytes,0,count);}if(total==0)throw new IOException("Empty image");return file;}catch(IOException e){file.delete();throw e;}}
    private Bitmap decodeScanBitmap(File file)throws IOException{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeFile(file.getAbsolutePath(),bounds);if(bounds.outWidth<1||bounds.outHeight<1||bounds.outWidth>30000||bounds.outHeight>30000)throw new IOException("Unsupported image dimensions");int sample=1;while(Math.max(bounds.outWidth/sample,bounds.outHeight/sample)>2200)sample*=2;BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=sample;Bitmap bitmap=BitmapFactory.decodeFile(file.getAbsolutePath(),options);if(bitmap==null)throw new IOException("Cannot decode image");try{int rotation=0;try{android.media.ExifInterface exif=new android.media.ExifInterface(file.getAbsolutePath());int orientation=exif.getAttributeInt(android.media.ExifInterface.TAG_ORIENTATION,android.media.ExifInterface.ORIENTATION_NORMAL);if(orientation==android.media.ExifInterface.ORIENTATION_ROTATE_90)rotation=90;else if(orientation==android.media.ExifInterface.ORIENTATION_ROTATE_180)rotation=180;else if(orientation==android.media.ExifInterface.ORIENTATION_ROTATE_270)rotation=270;}catch(Exception ignored){}if(rotation!=0){Matrix matrix=new Matrix();matrix.postRotate(rotation);Bitmap rotated=Bitmap.createBitmap(bitmap,0,0,bitmap.getWidth(),bitmap.getHeight(),matrix,true);if(rotated!=bitmap){bitmap.recycle();bitmap=rotated;}}return bitmap;}catch(RuntimeException|OutOfMemoryError e){bitmap.recycle();throw e;}}
    private String tessDataPath()throws IOException{File root=new File(getFilesDir(),"paidflow-ocr"),dir=new File(root,"tessdata");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Cannot create OCR data directory");for(String language:new String[]{"eng","rus"}){File model=new File(dir,language+".traineddata");if(model.isFile()&&model.length()>100000)continue;File temp=new File(dir,language+".traineddata.tmp");try(InputStream in=getAssets().open("tessdata/"+language+".traineddata");FileOutputStream out=new FileOutputStream(temp)){byte[] bytes=new byte[8192];int count,total=0;while((count=in.read(bytes))!=-1){total+=count;out.write(bytes,0,count);}if(total<100000)throw new IOException("Invalid OCR model");}if(model.exists()&&!model.delete()||!temp.renameTo(model))throw new IOException("Cannot install OCR model");}return root.getAbsolutePath();}
    @Override protected void onSaveInstanceState(Bundle state){state.putString("scanTarget",scanTarget);state.putString("scanDraft",scanDraft);state.putString("captureUri",captureUri==null?null:captureUri.toString());state.putString("pendingScanScript",pendingScanScript);super.onSaveInstanceState(state);}
    private void scanScript(String script){runOnUiThread(()->{if(pageReady&&web!=null)web.evaluateJavascript(script,null);else pendingScanScript=script;});}
    private void scanStatus(String target,String status,String text){scanScript("window.scanStatus&&window.scanStatus("+JSONObject.quote(target)+","+JSONObject.quote(status)+","+JSONObject.quote(text)+")");}
    private void onWebReady(){pageReady=true;
        if(restoreScanDraft){restoreScanDraft=false;web.evaluateJavascript("window.restoreScanDraft&&window.restoreScanDraft("+JSONObject.quote(scanDraft)+")",null);}
        if(!pendingScanScript.isEmpty()){String script=pendingScanScript;pendingScanScript="";web.evaluateJavascript(script,null);}
if(pendingShareUri!=null){Uri uri=pendingShareUri;pendingShareUri=null;recognizeInvoice(uri);}else receiveSharedImage(getIntent());}
    private void receiveSharedImage(Intent intent){if(shareHandled||intent==null||!Intent.ACTION_SEND.equals(intent.getAction()))return;String type=intent.getType();if(type==null||!type.startsWith("image/"))return;Uri uri=null;try{Object stream=intent.getParcelableExtra(Intent.EXTRA_STREAM);if(stream instanceof Uri)uri=(Uri)stream;}catch(Exception ignored){}if(uri==null&&intent.getClipData()!=null&&intent.getClipData().getItemCount()>0)uri=intent.getClipData().getItemAt(0).getUri();if(uri==null)return;shareHandled=true;if(pageReady)recognizeInvoice(uri);else pendingShareUri=uri;}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);shareHandled=false;receiveSharedImage(intent);}
    private void recognizeInvoice(Uri uri){recognizeDocument(uri,null,"invoice");}
    private void recognizeDocument(Uri uri,File cameraOutput,String target){scanBusy=true;scanStatus(target,"busy",t("Распознаю текст на телефоне. Это может занять до минуты…","Reading text on this phone. This may take up to a minute…"));new Thread(()->{File imageFile=null;Bitmap bitmap=null;TessBaseAPI tess=null;try{imageFile=copyScanImage(uri);bitmap=decodeScanBitmap(imageFile);tess=new TessBaseAPI();if(!tess.init(tessDataPath(),"rus+eng"))throw new IOException("OCR initialization failed");tess.setImage(bitmap);String text=tess.getUTF8Text();if(text==null||text.trim().length()<2)throw new IOException("No text found");String result=text.length()>12000?text.substring(0,12000):text;String callback="client".equals(target)?"openClientRequisitesFromScan":"openInvoiceFromScan";scanScript("window."+callback+"&&window."+callback+"("+JSONObject.quote(result)+")");}catch(Throwable e){android.util.Log.e("PaidFlowScan","Document recognition failed",e);String reason=e.getMessage();String error="No text found".equals(reason)?t("На фото не найден текст. Сними документ целиком, при хорошем освещении и без размытия.","No text found. Photograph the whole document in good light and in focus."):e instanceof FileNotFoundException?t("Не удалось прочитать фото. Повтори съёмку или выбери изображение из галереи.","Could not read the photo. Retake it or choose an image from your gallery."):t("Не удалось распознать фото. Повтори съёмку или выбери другое изображение. Данные формы сохранены.","Could not recognize the photo. Retake it or choose another image. Your form is preserved.");scanStatus(target,"error",error);}finally{if(tess!=null)tess.recycle();if(bitmap!=null&&!bitmap.isRecycled())bitmap.recycle();if(imageFile!=null)imageFile.delete();if(cameraOutput!=null)cameraOutput.delete();runOnUiThread(()->{scanBusy=false;if(!restoreScanDraft)scanDraft="";});}} ,"paidflow-ocr").start();}

    final class Bridge {
        @JavascriptInterface public synchronized String load(){try{return new String(dataFile.readFully(),StandardCharsets.UTF_8);}catch(FileNotFoundException e){return "";}catch(Exception e){return "__READ_ERROR__";}}
        @JavascriptInterface public synchronized boolean save(String json){FileOutputStream out=null;try{byte[] bytes=json.getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX)return false;JSONObject root=new JSONObject(json);if(root.getInt("schema")!=1||root.getJSONArray("clients").length()>10000||root.getJSONArray("invoices").length()>10000)return false;out=dataFile.startWrite();out.write(bytes);dataFile.finishWrite(out);return true;}catch(Exception e){if(out!=null)dataFile.failWrite(out);return false;}}
        @JavascriptInterface public void copy(String text){if(text.length()>5000)return;runOnUiThread(()->((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("PaidFlow",text)));}
        @JavascriptInterface public void share(String text){if(text.length()>5000)return;runOnUiThread(()->{try{startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text),t("Отправить напоминание","Share reminder")));}catch(Exception e){message(t("Не удалось открыть приложение для отправки","Could not open a sharing app"));}});}
        @JavascriptInterface public void exportBackup(String json){try{byte[] bytes=json.getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX)throw new IOException();try(FileOutputStream out=new FileOutputStream(new File(getCacheDir(),"export.json"))){out.write(bytes);}runOnUiThread(()->{try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/json").putExtra(Intent.EXTRA_TITLE,"PaidFlow-backup.json"),EXPORT);}catch(Exception e){message(t("Не удалось открыть выбор файла","Could not open the file picker"));}});}catch(Exception e){message(t("Не удалось подготовить копию","Could not prepare backup"));}}
        @JavascriptInterface public void scanInvoice(String draft){chooseScanImage("invoice",draft);}
        @JavascriptInterface public void scanClientRequisites(String draft){chooseScanImage("client",draft);}
        @JavascriptInterface public void importBackup(){runOnUiThread(()->{try{startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*"),IMPORT);}catch(Exception e){message(t("Не удалось открыть выбор файла","Could not open the file picker"));}});}
        @JavascriptInterface public void printInvoice(String html,String name){if(html.length()>1000000||!name.matches("PF-[0-9]+"))return;runOnUiThread(()->{
            if(printWeb!=null){printWeb.destroy();printWeb=null;}printWeb=new WebView(MainActivity.this);printWeb.getSettings().setJavaScriptEnabled(false);printWeb.getSettings().setAllowFileAccess(false);printWeb.getSettings().setAllowContentAccess(false);
            printWeb.setWebViewClient(new WebViewClient(){boolean printed=false;@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}@Override public void onPageFinished(WebView v,String url){if(printed)return;printed=true;try{PrintManager manager=(PrintManager)getSystemService(PRINT_SERVICE);manager.print(name,v.createPrintDocumentAdapter(name),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).setColorMode(PrintAttributes.COLOR_MODE_COLOR).build());message(t("В окне печати выбери «Сохранить как PDF»","Choose Save as PDF in the print dialog"));}catch(Exception e){message(t("Печать недоступна на этом устройстве","Printing is unavailable on this device"));}}});
            printWeb.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);
        });}
    }
    @Override protected void onActivityResult(int request,int result,Intent intent){super.onActivityResult(request,result,intent);if(request==SCAN){File output=captureFile;Uri uri=output!=null&&output.length()>0?captureUri:intent!=null&&intent.getData()!=null?intent.getData():captureUri;captureFile=null;captureUri=null;String target=scanTarget;if(result!=RESULT_OK){if(output!=null)output.delete();scanStatus(target,"cancelled",t("Съёмка отменена. Можно попробовать снова.","Capture cancelled. You can try again."));return;}if(uri==null){if(output!=null)output.delete();scanStatus(target,"error",t("Изображение не получено. Повтори съёмку или выбери файл.","No image received. Retake the photo or choose a file."));return;}recognizeDocument(uri,output,target);return;}if(result!=RESULT_OK||intent==null||intent.getData()==null)return;Uri uri=intent.getData();new Thread(()->{try{if(request==EXPORT){byte[] bytes=read(new FileInputStream(new File(getCacheDir(),"export.json")));try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException();out.write(bytes);}message(t("Резервная копия сохранена","Backup saved"));}else if(request==IMPORT){String json=new String(read(getContentResolver().openInputStream(uri)),StandardCharsets.UTF_8);runOnUiThread(()->{if(web!=null)web.evaluateJavascript("window.receiveBackup("+JSONObject.quote(json)+")",null);});}}catch(Exception e){message(t("Не удалось прочитать или записать файл. Данные приложения не изменены.","Could not read or write the file. App data was not changed."));}},"paidflow-files").start();}
    @Override public void onBackPressed(){web.evaluateJavascript("window.handleBack ? window.handleBack() : false",value->{if(!"true".equals(value))finish();});}
    @Override protected void onDestroy(){if(web!=null){web.removeJavascriptInterface("Native");web.destroy();web=null;}if(printWeb!=null){printWeb.destroy();printWeb=null;}super.onDestroy();}
}
