const test=require('node:test'),assert=require('node:assert/strict');const P=require('../app/src/main/assets/core.js');
function fixture(){let disk='';const s=new P.Store(P.empty(),raw=>disk=raw);s.saveSettings({...s.data.settings,business:'Test Studio'});const client=s.saveClient({name:'Customer',email:'a@example.com',phone:'',notes:''});return {s,client,disk:()=>disk};}
function invoice(s,client,due=P.today(),currency='USD'){return s.create({clientId:client,due,currency,items:[{name:'Service',qty:3,unit:101}],notes:''});}
test('exact money parsing and fractional precision',()=>{assert.equal(P.amount('0.10'),10);assert.equal(P.amount('1234,56'),123456);assert.equal(P.lineTotal({unit:10,qty:3}),30);for(const v of ['0','-1','1.001','1e3','NaN','1,000.00','99999999999999'])assert.throws(()=>P.amount(v));});
test('invoice OCR parser reads Russian client, due date, currency and item rows',()=>{const found=P.parseInvoiceText('СЧЁТ № 18\nПокупатель: ООО Ромашка ИНН 7701234567\nСрок оплаты: 12.02.2025\nНаименование Количество Цена Сумма\nРазработка сайта 2 15 000,00 30 000,00 ₽\nИтого к оплате 30 000,00 руб.');assert.equal(found.clientName,'ООО Ромашка');assert.equal(found.due,'2025-02-12');assert.equal(found.currency,'RUB');assert.deepEqual(found.items,[{name:'Разработка сайта',qty:2,unit:1500000}]);assert.equal(found.total,3000000);});
test('invoice OCR parser supports English text and a total-only invoice',()=>{const found=P.parseInvoiceText('Customer: Acme Studio\nDue date: 2026-11-05\nBank instructions: RUB transfer accepted\nTotal: $1,250.50');assert.equal(found.clientName,'Acme Studio');assert.equal(found.due,'2026-11-05');assert.equal(found.currency,'USD');assert.deepEqual(found.items,[{name:'Услуги по счёту',qty:1,unit:125050}]);assert.equal(found.total,125050);});
test('invoice OCR parser ignores invalid dates and empty or implausible totals',()=>{const found=P.parseInvoiceText('Срок оплаты: 31.02.2025\nИтого к оплате: 0');assert.equal(found.due,null);assert.deepEqual(found.items,[]);assert.equal(found.total,null);});
test('quantity and total bounds',()=>{for(const q of [0,-1,1.5,100001])assert.throws(()=>P.lineTotal({unit:1,qty:q}));assert.throws(()=>P.lineTotal({unit:P.MAX,qty:2}));});
test('due today is pending, overdue becomes paid after two payments',()=>{const {s,client}=fixture();const id=invoice(s,client);assert.equal(P.status(s.invoice(id)),'pending');assert.equal(P.status(s.invoice(id),P.addDays(1)),'overdue');s.payment(id,100,P.today(),'cash');assert.equal(P.balance(s.invoice(id)),203);assert.equal(P.status(s.invoice(id)),'partial');assert.throws(()=>s.payment(id,204,P.today(),''));assert.throws(()=>s.payment(id,1,P.addDays(1),''));s.payment(id,203,P.today(),'bank');assert.equal(P.status(s.invoice(id)),'paid');s.removePayment(id,s.invoice(id).payments[1].id);assert.equal(P.balance(s.invoice(id)),203);});
test('cancel excludes payments and can be restored',()=>{const {s,client}=fixture();const id=invoice(s,client);s.cancel(id);assert.equal(P.status(s.invoice(id)),'cancelled');assert.throws(()=>s.payment(id,1,P.today(),''));s.cancel(id);s.payment(id,1,P.today(),'');assert.throws(()=>s.cancel(id));});
test('client and seller snapshot never change past invoices',()=>{const {s,client}=fixture();const id=invoice(s,client);s.saveClient({name:'Changed',email:'',phone:'',notes:''},client);s.saveSettings({...s.data.settings,business:'Changed Studio'});assert.equal(s.invoice(id).client.name,'Customer');assert.equal(s.invoice(id).seller.business,'Test Studio');});
test('invalid restore leaves memory and persistence unchanged',()=>{const {s,client,disk}=fixture();invoice(s,client);const before=disk();let d=JSON.parse(before);d.invoices[0].items[0].qty=-1;assert.throws(()=>s.restore(JSON.stringify(d)));assert.equal(disk(),before);assert.equal(JSON.stringify(s.data),before);d=JSON.parse(before);d.invoices[0].clientId='missing';assert.throws(()=>s.restore(JSON.stringify(d)));d=JSON.parse(before);d.invoices[0].items[0].unit=1.1;assert.throws(()=>s.restore(JSON.stringify(d)));});
test('persistence failure leaves state intact',()=>{const {s,client}=fixture();const before=JSON.stringify(s.data);s.persist=()=>{throw Error('disk full');};assert.throws(()=>invoice(s,client));assert.equal(JSON.stringify(s.data),before);});
test('backup roundtrip, unique invoice numbers and currencies',()=>{const {s,client,disk}=fixture();const a=invoice(s,client,P.today(),'USD'),b=invoice(s,client,P.today(),'KZT');s.cancel(a);const r=new P.Store(JSON.parse(disk()));assert.equal(r.invoice(a).cancelled,true);assert.equal(r.invoice(b).currency,'KZT');assert.equal(r.invoice(invoice(r,client)).seq,3);});
test('dates and duplicate references are strictly checked',()=>{assert.equal(P.dateOK('2026-02-29'),false);assert.equal(P.dateOK('2028-02-29'),true);const {s,client}=fixture();invoice(s,client);let d=JSON.parse(JSON.stringify(s.data));d.invoices.push(d.invoices[0]);assert.throws(()=>P.validate(d));});
test('reminders are explicit records and cannot target settled invoices',()=>{const {s,client}=fixture();const id=invoice(s,client);assert.equal(s.invoice(id).reminders.length,0);s.remind(id,'Hello');assert.equal(s.invoice(id).reminders.length,1);s.payment(id,303,P.today(),'');assert.throws(()=>s.remind(id,'Again'));});
test('invoice edits retain number, date, payment history and sender',()=>{const {s,client}=fixture();const id=invoice(s,client);s.payment(id,100,P.today(),'deposit');const before=s.invoice(id);s.editInvoice(id,{clientId:client,currency:'USD',due:P.addDays(3),notes:'Fixed',items:[{name:'Corrected',unit:200,qty:2}]});const after=s.invoice(id);assert.equal(P.balance(after),300);assert.equal(after.seq,before.seq);assert.equal(after.created,before.created);assert.deepEqual(after.payments,before.payments);assert.deepEqual(after.seller,before.seller);});
test('edits below paid amount or currency/client changes are rejected atomically',()=>{const {s,client,disk}=fixture();const id=invoice(s,client);s.payment(id,100,P.today(),'');const before=disk();const input={clientId:client,currency:'USD',due:P.today(),notes:'',items:[{name:'Small',unit:99,qty:1}]};assert.throws(()=>s.editInvoice(id,input),/below-paid/);assert.equal(disk(),before);assert.throws(()=>s.editInvoice(id,{...input,currency:'KZT'}),/paid-fields/);const other=s.saveClient({name:'Other',email:'',phone:'',notes:''});assert.throws(()=>s.editInvoice(id,{...input,clientId:other}),/paid-fields/);});
test('unpaid invoices may switch clients and currency; cancelled ones require restoration',()=>{const {s,client}=fixture();const id=invoice(s,client),other=s.saveClient({name:'Other',email:'',phone:'',notes:''});const input={clientId:other,currency:'KZT',due:P.today(),notes:'',items:[{name:'Fixed',unit:50,qty:1}]};s.editInvoice(id,input);assert.equal(s.invoice(id).client.name,'Other');assert.equal(s.invoice(id).currency,'KZT');s.cancel(id);assert.throws(()=>s.editInvoice(id,input),/closed/);});

test('invoice OCR handles 1C-style numbered rows, grouped amounts and tenge',()=>{const found=P.parseInvoiceText('Счёт № 45\nПокупатель: ТОО Поставка\nНаименование Количество Цена Сумма\n1. Услуга монтажа 2 шт. 125 000,00 250 000,00 тг.\nВсего к оплате:\n250000.00 KZT');assert.equal(found.clientName,'ТОО Поставка');assert.equal(found.currency,'KZT');assert.deepEqual(found.items,[{name:'Услуга монтажа',qty:2,unit:12500000}]);assert.equal(found.total,25000000);assert.equal(found.declaredTotal,25000000);});
test('client requisites OCR extracts Kazakhstan company and bank fields',()=>{const found=P.parseClientRequisitesText('Получатель: ТОО «Альфа Сервис»\nБИН: 123456789012\nЮридический адрес: г. Алматы, ул. Абая, 10\nИИК: KZ123456789012345678\nБИК банка: KCJBKZKX\nКБЕ: 17\nБанк получателя: АО Банк ЦентрКредит\nEmail: office@example.kz\nТелефон: +7 (727) 123-45-67');assert.deepEqual(found,{name:'ТОО «Альфа Сервис»',email:'office@example.kz',phone:'+7 (727) 123-45-67',binIin:'123456789012',address:'г. Алматы, ул. Абая, 10',account:'KZ123456789012345678',bic:'KCJBKZKX',kbe:'17',bank:'АО Банк ЦентрКредит'});});
test('new client requisites persist and older local backups remain readable',()=>{const old=P.empty();old.settings.business='Studio';old.clients.push({id:'legacy-client',name:'Legacy',email:'',phone:'',notes:''});const legacy=new P.Store(old);const id=legacy.saveClient({name:'NewCo',email:'',phone:'',notes:'',binIin:'123456789012',address:'Almaty',account:'KZ123456789012345678',bic:'KCJBKZKX',kbe:'17',bank:'Example Bank'});legacy.create({clientId:'legacy-client',due:P.addDays(7),currency:'USD',items:[{name:'Work',qty:1,unit:100}],notes:''});legacy.create({clientId:id,due:P.addDays(7),currency:'USD',items:[{name:'Work',qty:1,unit:100}],notes:''});const copy=new P.Store(JSON.parse(JSON.stringify(legacy.data)));assert.equal(copy.data.clients.find(c=>c.id===id).account,'KZ123456789012345678');assert.equal(copy.data.invoices.length,2);});
