const {chromium}=require('playwright');
const path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},locale:'ru-RU'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/index.html'));
 await page.evaluate(()=>{store.saveSettings({...store.data.settings,business:'Test',language:'ru',currency:'KZT'});store.saveClient({name:'Existing',email:'',phone:'',notes:''});clientForm();});
 await page.locator('#notes').fill('Do not lose my draft');
 const draft=await page.evaluate(()=>captureScanDraft('client'));
 await page.evaluate(raw=>{closeModal();window.restoreScanDraft(raw);window.scanStatus('client','busy','Распознаю…');},draft);
 assert.equal(await page.locator('#notes').inputValue(),'Do not lose my draft');
 assert.equal(await page.locator('[data-action=scan-client]').isDisabled(),true);
 const card='Организация: ТОО Альфа\nБИН: 123456789012\nАдрес: Алматы, Абая 10\nИИК: KZ86125KZT5004100100\nБИК: HSBKKZKX\nКБе: 17\nБанк: Народный Банк\nТелефон: +7 700 123 45 67';
 await page.evaluate(raw=>window.openClientRequisitesFromScan(raw),card);
 assert.equal(await page.locator('#name').inputValue(),'ТОО Альфа');
 assert.equal(await page.locator('#binIin').inputValue(),'123456789012');
 assert.equal(await page.locator('#account').inputValue(),'KZ86125KZT5004100100');
 assert.equal(await page.locator('#bic').inputValue(),'HSBKKZKX');
 assert.equal(await page.locator('#kbe').inputValue(),'17');
 assert.equal(await page.locator('#notes').inputValue(),'Do not lose my draft');
 assert.equal(await page.locator('[data-action=scan-client]').isDisabled(),false);
 await page.evaluate(()=>window.scanStatus('client','error','Не удалось прочитать фото. Повтори съёмку.'));
 assert.equal(await page.locator('#client-scan-status').isVisible(),true);
 assert.match(await page.locator('#client-scan-status').textContent(),/Повтори/);
 await page.evaluate(()=>{closeModal();window.openClientRequisitesFromScan('Организация: ТОО Восстановлено');});
 assert.equal(await page.locator('#name').inputValue(),'ТОО Восстановлено');
 await page.evaluate(()=>invoiceForm());
 await page.locator('#invoice-note').fill('Invoice draft');
 await page.locator('.line-name').fill('Before camera');
 await page.locator('.line-price').fill('34.56');
 const invoiceDraft=await page.evaluate(()=>captureScanDraft('invoice'));
 await page.evaluate(raw=>{closeModal();window.restoreScanDraft(raw);},invoiceDraft);
 assert.equal(await page.locator('.line-name').inputValue(),'Before camera');
 assert.equal(await page.locator('.line-price').inputValue(),'34.56');
 await page.evaluate(()=>window.openInvoiceFromScan('Покупатель: ТОО Новый клиент\n1. Бумага 2 шт 1 200,00 2 400,00\nИтого: 2 400,00 KZT'));
 assert.equal(await page.locator('.line-name').inputValue(),'Бумага');
 assert.equal(await page.locator('.line-price').inputValue(),'1200.00');
 assert.equal(await page.locator('#invoice-note').inputValue(),'Invoice draft');
 assert.equal(await page.locator('#client').inputValue(),'');
 assert.equal(await page.locator('#inline-client-panel').isVisible(),true);
 assert.match(await page.locator('#scan-new-client').textContent(),/не найден.*Создать/);
 assert.equal(await page.evaluate(()=>store.data.clients.length),1);
 await page.locator('[data-action=save-inline-client]').click();
 assert.equal(await page.locator('#client option:checked').textContent(),'ТОО Новый клиент');
 assert.equal(await page.locator('.line-name').inputValue(),'Бумага');
 assert.equal(await page.evaluate(()=>store.data.clients.length),2);
 await page.evaluate(()=>window.openInvoiceFromScan('Покупатель: ТОО Новый клиент\nУслуга 1 200,00 200,00'));
 assert.equal(await page.locator('#inline-client-panel').isVisible(),false);
 assert.equal(await page.evaluate(()=>store.data.clients.length),2);
 await page.evaluate(()=>{document.querySelector('#client').disabled=true;document.querySelector('#inv-currency').disabled=true;window.openInvoiceFromScan('Покупатель: Existing\nИтого: 20 USD');});
 assert.equal(await page.locator('#client option:checked').textContent(),'ТОО Новый клиент');
 assert.equal(await page.locator('#inv-currency').inputValue(),'KZT');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 await page.screenshot({path:process.env.SCAN_SCREENSHOT||'/tmp/paidflow-scan-result.png'});
 console.log('Scan UI passed: draft recovery, 7 client fields, persistent error/retry, missing form recovery, invoice items, new/existing client, paid invoice locks.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
