const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
const assets=path.resolve(__dirname,'../app/src/main/assets'),out=process.env.QA_DIR||path.resolve(__dirname,'../../qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!['index.html','app.js','core.js','style.css'].includes(name)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(assets,name)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--renderer-process-limit=1']});const page=await browser.newPage({viewport:{width:390,height:844},locale:'ru-RU',deviceScaleFactor:2});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('button',{name:'Ещё',exact:true}).click();await page.getByLabel('Название / имя отправителя').fill('Artem Studio');await page.getByLabel('Адрес, телефон, email').fill('hello@example.com');await page.getByLabel('Реквизиты и инструкции для оплаты').fill('Банковский перевод по реквизитам исполнителя');await page.locator('#currency').selectOption('KZT');await page.getByRole('button',{name:'Сохранить настройки'}).click();
 await page.getByRole('button',{name:'Клиенты',exact:true}).click();await page.getByRole('button',{name:'+ Добавить клиента',exact:true}).click();await page.getByLabel('Имя / организация').fill('Northside Coffee');await page.getByLabel('Email',{exact:true}).fill('alex@example.com');await page.getByLabel('Телефон').fill('+7 700 123 45 67');await page.getByLabel('Заметки').fill('Обслуживание кофемашины');await page.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await page.locator('.card h3').textContent(),'Northside Coffee');
 await page.getByRole('button',{name:'Счета',exact:true}).click();await page.getByRole('button',{name:'+ Создать счёт',exact:true}).click();await page.locator('#due').fill('2026-01-01');await page.locator('.line-name').fill('Обслуживание кофемашины');await page.locator('.line-price').fill('85000');await page.getByRole('button',{name:'+ Добавить позицию'}).click();await page.locator('.line-name').nth(1).fill('Фильтр');await page.locator('.line-price').nth(1).fill('5000');await page.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await page.locator('h1').textContent(),'PF-0001');
 await page.getByRole('button',{name:'+ Записать оплату'}).click();await page.getByLabel('Сумма',{exact:true}).fill('20000');await page.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await page.evaluate(()=>PF.balance(store.invoice(detail))),7000000);
 await page.getByRole('button',{name:'Обзор',exact:true}).click();await page.screenshot({path:path.join(out,'01-overview.png')});
 await page.getByRole('button',{name:'Счета',exact:true}).click();await page.locator('#query').fill('missing');assert.equal(await page.locator('.invoice-card').count(),0);await page.locator('#query').fill('Northside');assert.equal(await page.locator('.invoice-card').count(),1);await page.screenshot({path:path.join(out,'02-invoices.png')});await page.locator('.invoice-card').click();await page.screenshot({path:path.join(out,'03-detail.png')});
 await page.getByRole('button',{name:'Подготовить напоминание'}).click();await page.screenshot({path:path.join(out,'04-reminder.png')});await page.getByRole('button',{name:'Я отправил — записать в журнал'}).click();assert.equal(await page.evaluate(()=>store.invoice(detail).reminders.length),1);
 await page.getByRole('button',{name:'Редактировать счёт',exact:true}).click();assert.equal(await page.locator('#client').isDisabled(),true);assert.equal(await page.locator('#inv-currency').isDisabled(),true);await page.locator('.line-price').first().fill('95000');await page.getByRole('button',{name:'Сохранить',exact:true}).click();assert.equal(await page.evaluate(()=>PF.balance(store.invoice(detail))),8000000);
 await page.getByRole('button',{name:'Счета',exact:true}).click();await page.getByRole('button',{name:'+ Создать счёт',exact:true}).click();await page.locator('.line-name').fill('Saved draft item');await page.locator('.line-price').fill('1234.56');await page.getByRole('button',{name:'+ Создать нового клиента',exact:true}).click();await page.locator('#ic-name').fill('Inline customer');await page.getByRole('button',{name:'Сохранить и выбрать клиента',exact:true}).click();assert.equal(await page.locator('.line-name').inputValue(),'Saved draft item');assert.equal(await page.locator('.line-price').inputValue(),'1234.56');assert.equal(await page.locator('#client option:checked').textContent(),'Inline customer');await page.getByRole('button',{name:'Закрыть',exact:true}).click();
 const backup=await page.evaluate(()=>JSON.stringify(store.data));await page.reload();assert.equal(await page.evaluate(()=>store.data.invoices.length),1);
 await page.evaluate(()=>window.receiveBackup('{"schema":99}'));assert.equal(await page.evaluate(()=>store.data.invoices.length),1);
 await page.evaluate(raw=>window.receiveBackup(raw),backup);await page.getByRole('button',{name:'Подтвердить',exact:true}).click();assert.equal(await page.evaluate(()=>store.data.invoices.length),1);
 await page.getByRole('button',{name:'Ещё',exact:true}).click();await page.locator('#language').selectOption('en');await page.getByRole('button',{name:'Сохранить настройки'}).click();await page.getByRole('button',{name:'Home',exact:true}).click();assert.equal(await page.locator('h1').textContent(),'Stay on top of payments');await page.screenshot({path:path.join(out,'05-english.png')});
 await page.evaluate(()=>{store.saveSettings({...store.data.settings,language:'ru'});render();});await page.getByRole('button',{name:'+ Создать счёт',exact:true}).click();await page.screenshot({path:path.join(out,'06-new-invoice.png')});await page.getByRole('button',{name:'Закрыть',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const html=await page.evaluate(()=>pdfHtml(store.data.invoices[0]));const pdf=await browser.newPage();await pdf.setContent(html);await pdf.pdf({path:path.join(out,'example-invoice.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});
 const longHtml=await page.evaluate(()=>{const i=store.invoice(store.data.invoices[0].id);i.items=Array.from({length:45},(_,n)=>({name:'Длинное описание услуги / Long service description '+(n+1),qty:2,unit:101}));return pdfHtml(i);});await pdf.setContent(longHtml);await pdf.pdf({path:path.join(out,'long-invoice.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});await pdf.close();
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'ui-result.json'),JSON.stringify({passed:true,checks:['client creation','invoice creation with two lines','partial payment balance','search','manual reminder log','reload persistence','invalid import rejection','backup restore','RU/EN','390px viewport','PDF generation'],errors},null,2));console.log('UI workflow passed; screenshots and PDF exported.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
